version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore ./src/dotnet-webapi-fibonacci.csproj
     - run:
         name: Build App
         command:
           dotnet build ./src/dotnet-webapi-fibonacci.csproj
     - run:
         name: Run Tests
         command:
           dotnet test ./test/dotnet-webapi-fibonacci-test.csproj