FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "dotnet-webapi-fibonacci.dll"]

# FROM microsoft/dotnet:2.2-aspnetcore-runtime
# WORKDIR /app
# COPY . .
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet dotnet-webapi-fibonacci.dll
